import test from'node:test';import assert from'node:assert/strict';import sharp from'sharp';import{convertPdf,inspectPdf,pdfError}from'../server/pdf.js';
function makePdf(pageCount=1,text='MENU'){const objects=[],fontId=3+pageCount*2;objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Kids [${Array.from({length:pageCount},(_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${pageCount} >>`;for(let i=0;i<pageCount;i++){const pageId=3+i*2,contentId=pageId+1,value=Array.isArray(text)?text[i]:`${text} ${i+1}`,stream=value?`BT /F1 8 Tf 50 720 Td (${value}) Tj ET`:'';objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`}objects[fontId]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=Buffer.byteLength(pdf);pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf)}
const payload=(buffer,name='menu.pdf')=>({name,type:'application/pdf',size:buffer.length,dataUrl:`data:application/pdf;base64,${buffer.toString('base64')}`});
test('PDF a una pagina produce PNG valido e JPEG normalizzato per Vision',async()=>{const pdf=payload(makePdf());const info=await inspectPdf(pdf),result=await convertPdf(pdf,{includeRenderedPng:true}),png=Buffer.from(result.pages[0].renderedPngDataUrl.split(',')[1],'base64');assert.equal(info.pageCount,1);assert.match(info.thumbnail,/^data:image\/jpeg;base64,/);assert.equal(result.pages.length,1);assert.deepEqual([...png.subarray(0,8)],[137,80,78,71,13,10,26,10]);assert.match(result.pages[0].dataUrl,/^data:image\/jpeg;base64,/)});
test('PDF multipagina mantiene ordine e pageNumber',async()=>{const result=await convertPdf(payload(makePdf(3)));assert.deepEqual(result.pages.map(x=>x.pageNumber),[1,2,3])});
test('PDF con colonne e testo piccolo conserva alta risoluzione',async()=>{const result=await convertPdf(payload(makePdf(1,'ANTIPASTI       PRIMI       8,50'))),image=Buffer.from(result.pages[0].dataUrl.split(',')[1],'base64'),metadata=await sharp(image).metadata();assert.ok(metadata.width>=1800);assert.ok(metadata.height>=2300);assert.equal(metadata.hasAlpha,false);assert.equal(metadata.space,'srgb')});
test('una pagina vuota non blocca le altre pagine',async()=>{const result=await convertPdf(payload(makePdf(2,['MENU',''])));assert.deepEqual(result.pages.map(x=>x.pageNumber),[1]);assert.match(result.warnings[0],/Pagina 2: pagina vuota/)});
test('PDF corrotto viene rifiutato',async()=>await assert.rejects(()=>inspectPdf(payload(Buffer.from('%PDF-corrotto'))),x=>x.code==='pdf_corrupt'));
test('PDF troppo grande rispetta il limite configurabile',async()=>{const old=process.env.PDF_MAX_BYTES;process.env.PDF_MAX_BYTES='100';try{await assert.rejects(()=>inspectPdf(payload(makePdf())),x=>x.code==='pdf_too_large')}finally{if(old===undefined)delete process.env.PDF_MAX_BYTES;else process.env.PDF_MAX_BYTES=old}});
test('PDF protetto produce un errore chiaro',()=>assert.equal(pdfError({name:'PasswordException',message:'password'}).code,'pdf_password_protected'));
test('numero massimo pagine è configurabile',async()=>{const old=process.env.PDF_MAX_PAGES;process.env.PDF_MAX_PAGES='1';try{await assert.rejects(()=>inspectPdf(payload(makePdf(2))),x=>x.code==='pdf_too_many_pages')}finally{if(old===undefined)delete process.env.PDF_MAX_PAGES;else process.env.PDF_MAX_PAGES=old}});
