import http from'node:http';import{readFile}from'node:fs/promises';import{extname,join,resolve}from'node:path';import{fileURLToPath}from'node:url';

const PORT=process.env.PORT||5173,root=resolve('.'),limit=45*1024*1024;
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webmanifest':'application/manifest+json'};
const send=(res,status,data)=>{const payload=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(payload)};
const devLog=(label,data)=>{if(process.env.NODE_ENV!=='production')console.info(`[RestMenu PDF] ${label}`,data)};

async function loadLocalEnv(){try{const env=await readFile(resolve('.env'),'utf8');for(const line of env.split(/\r?\n/)){const m=line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')}}catch{}}
async function body(req){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>limit)throw Object.assign(new Error('Il caricamento supera il limite di 45 MB.'),{status:413});chunks.push(c)}return JSON.parse(Buffer.concat(chunks).toString('utf8'))}

let envReady,visionPromise,pdfPromise,vitePromise;
const vision=()=>visionPromise??=import('./vision.js');
const pdfTools=()=>pdfPromise??=import('./pdf.js');
const vite=()=>vitePromise??=import('vite').then(({createServer})=>createServer({server:{middlewareMode:true},appType:'spa'}));

export async function processScanData(data,{loadVision=vision,loadPdf=pdfTools}={}){const hasImages=Array.isArray(data.images)&&data.images.length>0,hasPdf=Boolean(data.pdf);if(hasImages===hasPdf)throw Object.assign(new Error('Invia fotografie oppure un PDF, senza mischiarli.'),{status:400});const{analyzePage,mergePages}=await loadVision(),sourceImages=[],analyzedPages=[],warnings=[],visionErrors=[];
  if(hasImages){if(data.images.length>12)throw Object.assign(new Error('Invia da 1 a 12 immagini.'),{status:400});sourceImages.push(...data.images.map((image,index)=>({page:image.page||index+1,dataUrl:image.dataUrl,mimeType:image.dataUrl?.slice(5,image.dataUrl.indexOf(';'))})))}
  else{const converted=await(await loadPdf()).convertPdf(data.pdf);sourceImages.push(...converted.pages);warnings.push(...converted.warnings)}
  for(const image of sourceImages){if(typeof image.dataUrl!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(image.dataUrl))throw Object.assign(new Error(`Formato immagine non valido alla pagina ${image.page}.`),{status:400,code:'invalid_rendered_image'});if(hasPdf)devLog('passaggio a Vision',{pageNumber:image.page,mimeType:image.mimeType,dataUrlLength:image.dataUrl.length,addedToVisionArray:true,pngSignatureValid:image.diagnostics?.pngSignatureValid,canvas:image.diagnostics?.canvas,viewport:image.diagnostics?.viewport,pngBytes:image.diagnostics?.pngBytes,normalization:image.diagnostics?.normalization});try{analyzedPages.push(await analyzePage(image.dataUrl,image.page,{mode:process.env.VISION_SCAN_MODE||'high_accuracy',source:hasPdf?'pdf':'photo'}));if(hasPdf)devLog('Vision completata',{pageNumber:image.page})}catch(error){if(!hasPdf)throw error;visionErrors.push({pageNumber:image.page,message:error.message,code:error.code||'vision_failed',type:error.type,status:error.status,requestId:error.requestId,stage:error.stage,phase:error.phase,functionName:error.functionName,durationMs:error.durationMs,valueDetails:error.valueDetails});warnings.push(`Pagina ${image.page}: analisi Vision non riuscita.`);devLog('errore Vision',{pageNumber:image.page,status:error.status,code:error.code,type:error.type||error.name,message:error.message,requestId:error.requestId,stage:error.stage,phase:error.phase,functionName:error.functionName,durationMs:error.durationMs,valueDetails:error.valueDetails,stack:error.stack})}}
  if(!analyzedPages.length){const technical=`PDF letto correttamente: ${sourceImages.length} pagine renderizzate. Rendering riuscito: ${sourceImages.length}/${sourceImages.length}. Vision riuscita: 0/${sourceImages.length}. Errori: ${JSON.stringify(visionErrors)}`,message=process.env.NODE_ENV==='production'?'Le pagine del PDF sono state convertite, ma non è stato possibile analizzarle. Riprova oppure esporta il PDF come immagini.':technical;throw Object.assign(new Error(message),{status:422,code:'pdf_vision_failed',technical,fallbackAvailable:false})}
  const result=mergePages(analyzedPages);result.warnings=[...warnings,...result.warnings];if(hasPdf){delete result.debug;result.pdf={filename:data.pdf.name,pageCount:sourceImages.length,mimeType:data.pdf.type,size:data.pdf.size}}return result}

const publicPdfCode=code=>code==='pdf_vision_failed'?'PDF_VISION_FAILED':code==='pdf_no_renderable_pages'||code==='pdf_render_failed'?'PDF_RENDER_FAILED':code?.startsWith('pdf_')?'PDF_INVALID':code;
async function inspect(req,res,{loadPdf=pdfTools}){try{const data=await body(req),tools=await loadPdf(),result=await tools.inspectPdf(data.pdf);send(res,200,{pageCount:result.pageCount})}catch(e){send(res,e.status||500,{error:e.message,code:publicPdfCode(e.code)||'PDF_INVALID',...(process.env.NODE_ENV!=='production'&&e.technical?{technical:e.technical}:{})})}}
async function api(req,res,deps){try{await(envReady??Promise.resolve());send(res,200,await processScanData(await body(req),deps))}catch(e){send(res,e.status||500,{error:e.message,code:publicPdfCode(e.code)||'scan_failed',fallbackAvailable:e.fallbackAvailable??!e.code?.startsWith('pdf_'),...(process.env.NODE_ENV!=='production'&&e.technical?{technical:e.technical}:{})})}}

export function createRestMenuServer(deps={}){return http.createServer(async(req,res)=>{if(req.method==='POST'&&req.url==='/api/scan')return api(req,res,deps);if(req.method==='POST'&&req.url==='/api/pdf/inspect')return inspect(req,res,deps);if(process.env.NODE_ENV!=='production'){const dev=await vite();return dev.middlewares(req,res)}try{const path=req.url==='/'?'index.html':req.url.split('?')[0].replace(/^\//,''),file=join(root,'dist',path);try{const data=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(data)}catch{const data=await readFile(join(root,'dist','index.html'));res.writeHead(200,{'Content-Type':'text/html'});res.end(data)}}catch{res.writeHead(500);res.end('Server error')}})}

const direct=process.argv[1]&&resolve(process.argv[1])===resolve(fileURLToPath(import.meta.url));
if(direct){const server=createRestMenuServer();server.listen(PORT,'0.0.0.0',()=>console.log(`RestMenu server listening on port ${PORT}`));envReady=loadLocalEnv()}
