import{createCanvas,DOMMatrix,ImageData,Path2D}from'@napi-rs/canvas';import sharp from'sharp';
if(!globalThis.DOMMatrix)globalThis.DOMMatrix=DOMMatrix;if(!globalThis.ImageData)globalThis.ImageData=ImageData;if(!globalThis.Path2D)globalThis.Path2D=Path2D;

export const pdfLimits=()=>({maxBytes:Number(process.env.PDF_MAX_BYTES||20*1024*1024),maxPages:Number(process.env.PDF_MAX_PAGES||30),renderScale:Math.min(4,Math.max(1,Number(process.env.PDF_RENDER_SCALE||3)))});
export function pdfError(error){if(error?.name==='PasswordException'||/password/i.test(error?.message||''))return Object.assign(new Error('Il PDF è protetto da password. Carica una copia senza protezione.'),{status:400,code:'pdf_password_protected'});if(error?.code)return error;return Object.assign(new Error('Il PDF è corrotto o non può essere letto.'),{status:400,code:'pdf_corrupt'})}
function decode({dataUrl,name,size,type}){const limits=pdfLimits();if(type!=='application/pdf'||!dataUrl?.startsWith('data:application/pdf;base64,')||!name?.toLowerCase().endsWith('.pdf'))throw Object.assign(new Error('Seleziona un file PDF valido.'),{status:400,code:'pdf_invalid_type'});const buffer=Buffer.from(dataUrl.slice(dataUrl.indexOf(',')+1),'base64');if(!buffer.subarray(0,5).equals(Buffer.from('%PDF-')))throw Object.assign(new Error('Il file non contiene un PDF valido.'),{status:400,code:'pdf_corrupt'});if(buffer.length>limits.maxBytes||Number(size)>limits.maxBytes)throw Object.assign(new Error(`Il PDF supera il limite di ${Math.round(limits.maxBytes/1024/1024)} MB.`),{status:413,code:'pdf_too_large'});return{buffer,limits}}
async function openPdf(pdf){const{buffer,limits}=decode(pdf);try{const{getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=getDocument({data:new Uint8Array(buffer),disableWorker:true,stopAtErrors:true,useSystemFonts:true});let protectedPdf=false;task.onPassword=()=>{protectedPdf=true;task.destroy()};let document;try{document=await task.promise}catch(error){if(protectedPdf)throw{name:'PasswordException',message:'password required'};throw error}if(!document.numPages){await task.destroy();throw Object.assign(new Error('Il PDF non contiene pagine.'),{status:400,code:'pdf_empty'})}if(document.numPages>limits.maxPages){await task.destroy();throw Object.assign(new Error(`Il PDF contiene ${document.numPages} pagine. Il limite è ${limits.maxPages}.`),{status:413,code:'pdf_too_many_pages'})}return{document,task,limits}}catch(error){throw pdfError(error)}}
const pngSignature=Buffer.from([137,80,78,71,13,10,26,10]);
export const isValidPng=buffer=>Buffer.isBuffer(buffer)&&buffer.length>pngSignature.length&&buffer.subarray(0,8).equals(pngSignature);
const devLog=data=>{if(process.env.NODE_ENV!=='production')console.info('[RestMenu PDF]',data)};
async function renderPage(document,pageNumber,scale){let details={pageNumber,mimeType:'image/png',bufferEmpty:true,pngSignatureValid:false};try{const page=await document.getPage(pageNumber),base=page.getViewport({scale:1});if(!Number.isFinite(base.width)||!Number.isFinite(base.height)||base.width<=0||base.height<=0)throw new Error(`Viewport PDF non valido: ${base.width}x${base.height}`);const operatorList=await page.getOperatorList();if(!operatorList.fnArray.length)throw Object.assign(new Error('Pagina PDF senza contenuto renderizzabile.'),{code:'pdf_blank_page'});const safeScale=Math.min(scale,6000/Math.max(base.width,base.height)),viewport=page.getViewport({scale:safeScale}),width=Math.max(1,Math.ceil(viewport.width)),height=Math.max(1,Math.ceil(viewport.height)),canvas=createCanvas(width,height);details={...details,viewport:{width:viewport.width,height:viewport.height,scale:safeScale},canvas:{width:canvas.width,height:canvas.height}};await page.render({canvas,canvasContext:canvas.getContext('2d'),viewport,background:'rgb(255,255,255)'}).promise;const png=canvas.toBuffer('image/png');details={...details,pngBytes:png.length,bufferEmpty:png.length===0,pngSignatureValid:isValidPng(png)};if(!isValidPng(png))throw new Error(`Buffer PNG non valido (${png.length} byte).`);devLog({...details,addedToVisionInput:false});return{png,details}}catch(error){devLog({...details,renderError:error.message});throw error}}
const preview=png=>sharp(png).resize({width:720,height:960,fit:'inside',withoutEnlargement:true}).jpeg({quality:90}).toBuffer();
async function normalizeForVision(png){const before=await sharp(png).metadata(),buffer=await sharp(png).flatten({background:'#ffffff'}).toColourspace('srgb').resize({width:3840,height:3840,fit:'inside',withoutEnlargement:true}).jpeg({quality:94,chromaSubsampling:'4:4:4',mozjpeg:true}).toBuffer(),after=await sharp(buffer).metadata();return{buffer,details:{before:{width:before.width,height:before.height,bytes:png.length,mimeType:'image/png',hasAlpha:before.hasAlpha,channels:before.channels,colourspace:before.space},after:{width:after.width,height:after.height,bytes:buffer.length,mimeType:'image/jpeg',hasAlpha:after.hasAlpha,channels:after.channels,colourspace:after.space},maxSide:3840,quality:94}}}
export async function inspectPdf(pdf){const{document,task}=await openPdf(pdf);try{for(let pageNumber=1;pageNumber<=document.numPages;pageNumber++)try{const{png}=await renderPage(document,pageNumber,1.2);return{pageCount:document.numPages,thumbnail:`data:image/jpeg;base64,${(await preview(png)).toString('base64')}`,thumbnailPage:pageNumber}}catch{}return{pageCount:document.numPages,thumbnail:null,thumbnailPage:null}}finally{await task.destroy()}}
export async function convertPdf(pdf,{includeRenderedPng=false}={}){const{document,task,limits}=await openPdf(pdf),pageCount=document.numPages,pages=[],warnings=[],errors=[];try{for(let pageNumber=1;pageNumber<=pageCount;pageNumber++){try{const{png,details}=await renderPage(document,pageNumber,limits.renderScale),normalized=await normalizeForVision(png),dataUrl=`data:image/jpeg;base64,${normalized.buffer.toString('base64')}`,item={pageNumber,page:pageNumber,dataUrl,mimeType:'image/jpeg',preview:`data:image/jpeg;base64,${(await preview(png)).toString('base64')}`,diagnostics:{...details,normalization:normalized.details},...(includeRenderedPng?{renderedPngDataUrl:`data:image/png;base64,${png.toString('base64')}`}:{})};pages.push(item);devLog({...details,normalization:normalized.details,finalDataUrlLength:dataUrl.length,addedToVisionInput:true})}catch(error){errors.push({pageNumber,message:error.message,code:error.code||'pdf_render_failed'});warnings.push(`Pagina ${pageNumber}: ${error.code==='pdf_blank_page'?'pagina vuota ignorata':`conversione non riuscita (${error.message})`}.`)}}}finally{await task.destroy()}if(!pages.length){const technical=`PDF letto correttamente: ${pageCount} pagine. Rendering riuscito: 0/${pageCount}. Errore: ${errors.map(x=>`pagina ${x.pageNumber}: ${x.message}`).join('; ')||'sconosciuto'}`,message=process.env.NODE_ENV==='production'?'Non è stato possibile convertire le pagine del PDF in immagini. Prova a esportare nuovamente il documento.':technical;throw Object.assign(new Error(message),{status:422,code:'pdf_no_renderable_pages',technical})}return{pageCount,pages,warnings,errors}}
