import{createCanvas,DOMMatrix,ImageData,Path2D}from'@napi-rs/canvas';import sharp from'sharp';
if(!globalThis.DOMMatrix)globalThis.DOMMatrix=DOMMatrix;if(!globalThis.ImageData)globalThis.ImageData=ImageData;if(!globalThis.Path2D)globalThis.Path2D=Path2D;

export const pdfLimits=()=>({maxBytes:Number(process.env.PDF_MAX_BYTES||20*1024*1024),maxPages:Number(process.env.PDF_MAX_PAGES||30),renderScale:Math.min(4,Math.max(1,Number(process.env.PDF_RENDER_SCALE||3)))});
export function pdfError(error){if(error?.name==='PasswordException'||/password/i.test(error?.message||''))return Object.assign(new Error('Il PDF è protetto da password. Carica una copia senza protezione.'),{status:400,code:'pdf_password_protected'});if(error?.code)return error;return Object.assign(new Error('Il PDF è corrotto o non può essere letto.'),{status:400,code:'pdf_corrupt'})}
function decode({dataUrl,name,size,type}){const limits=pdfLimits();if(type!=='application/pdf'||!dataUrl?.startsWith('data:application/pdf;base64,')||!name?.toLowerCase().endsWith('.pdf'))throw Object.assign(new Error('Seleziona un file PDF valido.'),{status:400,code:'pdf_invalid_type'});const buffer=Buffer.from(dataUrl.slice(dataUrl.indexOf(',')+1),'base64');if(!buffer.subarray(0,5).equals(Buffer.from('%PDF-')))throw Object.assign(new Error('Il file non contiene un PDF valido.'),{status:400,code:'pdf_corrupt'});if(buffer.length>limits.maxBytes||Number(size)>limits.maxBytes)throw Object.assign(new Error(`Il PDF supera il limite di ${Math.round(limits.maxBytes/1024/1024)} MB.`),{status:413,code:'pdf_too_large'});return{buffer,limits}}
async function openPdf(pdf){const{buffer,limits}=decode(pdf);try{const{getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=getDocument({data:new Uint8Array(buffer),disableWorker:true,stopAtErrors:true,useSystemFonts:true});let protectedPdf=false;task.onPassword=()=>{protectedPdf=true;task.destroy()};let document;try{document=await task.promise}catch(error){if(protectedPdf)throw{name:'PasswordException',message:'password required'};throw error}if(!document.numPages){await task.destroy();throw Object.assign(new Error('Il PDF non contiene pagine.'),{status:400,code:'pdf_empty'})}if(document.numPages>limits.maxPages){await task.destroy();throw Object.assign(new Error(`Il PDF contiene ${document.numPages} pagine. Il limite è ${limits.maxPages}.`),{status:413,code:'pdf_too_many_pages'})}return{document,task,limits}}catch(error){throw pdfError(error)}}
async function renderPage(document,pageNumber,scale){const page=await document.getPage(pageNumber),base=page.getViewport({scale:1}),safeScale=Math.min(scale,6000/Math.max(base.width,base.height)),viewport=page.getViewport({scale:safeScale}),canvas=createCanvas(Math.max(1,Math.ceil(viewport.width)),Math.max(1,Math.ceil(viewport.height)));await page.render({canvas,canvasContext:canvas.getContext('2d'),viewport,background:'white'}).promise;const png=canvas.toBuffer('image/png'),stats=await sharp(png).resize({width:64,height:64,fit:'inside'}).stats(),visible=stats.channels.slice(0,3).some(x=>x.stdev>.65||x.mean<249);if(!visible)throw Object.assign(new Error('Pagina vuota.'),{code:'pdf_blank_page'});return png}
const preview=png=>sharp(png).resize({width:720,height:960,fit:'inside',withoutEnlargement:true}).jpeg({quality:90}).toBuffer();
export async function inspectPdf(pdf){const{document,task}=await openPdf(pdf);try{const png=await renderPage(document,1,1.2);return{pageCount:document.numPages,thumbnail:`data:image/jpeg;base64,${(await preview(png)).toString('base64')}`}}finally{await task.destroy()}}
export async function convertPdf(pdf,{onPage}={}){const{document,task,limits}=await openPdf(pdf),pageCount=document.numPages,pages=[],warnings=[];try{for(let pageNumber=1;pageNumber<=pageCount;pageNumber++){try{const png=await renderPage(document,pageNumber,limits.renderScale),item={pageNumber,dataUrl:`data:image/png;base64,${png.toString('base64')}`,preview:`data:image/jpeg;base64,${(await preview(png)).toString('base64')}`};if(onPage)await onPage(item);pages.push(onPage?{pageNumber,preview:item.preview}:item)}catch(error){warnings.push(`Pagina ${pageNumber}: ${error.code==='pdf_blank_page'?'pagina vuota ignorata':'conversione non riuscita'}.`)}}}finally{await task.destroy()}if(!pages.length)throw Object.assign(new Error('Nessuna pagina del PDF può essere analizzata.'),{status:400,code:'pdf_no_renderable_pages'});return{pageCount,pages,warnings}}
