import sharp from 'sharp';
import {layoutSchema,blockSchema,structuralValidationSchema} from './schema.js';

export const MAX_BLOCKS=10;
const MODEL=()=>process.env.OPENAI_MODEL||'gpt-5.6-terra';
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const priceNorm=s=>norm(s).replace(/\beur\b/g,'').trim();
const confValue={low:0,medium:1,high:2};
const fidelity=`Devi trascrivere e strutturare il contenuto visibile, non ricostruire il menu per intuizione. Se un'informazione non è chiaramente leggibile, non completarla. È preferibile restituire un valore incerto piuttosto che un valore plausibile ma inventato.`;
const OPENAI_ENDPOINT='https://api.openai.com/v1/responses';
const diagnosticLog=(event,data)=>{if(process.env.NODE_ENV!=='production')console.info(`[RestMenu Vision] ${event}`,data)};

function dataUrl(buffer){return `data:image/jpeg;base64,${buffer.toString('base64')}`}
export function validateImageDataUrl(value){
  if(typeof value!=='string')throw Object.assign(new TypeError('Il valore immagine deve essere una stringa.'),{status:400,code:'invalid_image_data_url'});
  const match=/^data:image\/jpeg;base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);
  if(!match||/[\r\n\s%]/.test(match?.[1]||''))throw Object.assign(new Error('Data URL JPEG non valido.'),{status:400,code:'invalid_image_data_url'});
  const buffer=Buffer.from(match[1],'base64');
  if(!buffer.length||buffer.toString('base64')!==match[1])throw Object.assign(new Error('Base64 JPEG non valido.'),{status:400,code:'invalid_image_base64'});
  return buffer;
}
function safeStringDetails(value){const string=typeof value==='string'?value:String(value);return{valueType:value===null?'null':Array.isArray(value)?'array':typeof value,stringPreview:string.slice(0,80),stringLength:string.length,mime:typeof value==='string'?value.match(/^data:([^;,]+)/)?.[1]||null:null,urlParser:'none'}}
function phaseError(error,phase,functionName,value){const details=safeStringDetails(value);diagnosticLog('errore fase',{phase,functionName,...details,errorType:error?.name||typeof error,message:error?.message,stack:error?.stack});if(!error.phase)error.phase=phase;if(!error.functionName)error.functionName=functionName;error.valueDetails=details;return error}
function decodeDataUrl(value){try{return validateImageDataUrl(value)}catch(error){throw phaseError(error,'decode_data_url','decodeDataUrl',value)}}
function outputText(json){if(typeof json.output_text==='string')return json.output_text;for(const out of json.output||[])for(const c of out.content||[])if(c.type==='output_text'&&c.text)return c.text;throw new Error('Risposta Vision priva di contenuto.')}
async function imageDiagnostics(image){if(!image)return null;const match=image.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)return{validDataUrl:false,length:image.length,containsNewline:/[\r\n]/.test(image)};const buffer=Buffer.from(match[2],'base64'),metadata=await sharp(buffer).metadata();return{validDataUrl:true,mimeType:match[1],dataUrlLength:image.length,base64Length:match[2].length,containsNewline:/[\r\n]/.test(match[2]),bytes:buffer.length,width:metadata.width,height:metadata.height,channels:metadata.channels,colourspace:metadata.space,hasAlpha:metadata.hasAlpha,format:metadata.format}}
async function callVision({prompt,image,schema,name,context={}}){
  if(!process.env.OPENAI_API_KEY)throw Object.assign(new Error('OPENAI_API_KEY non configurata. Puoi continuare con l’inserimento manuale.'),{status:503,code:'missing_api_key'});
  const userContent=[{type:'input_text',text:prompt}];if(image)userContent.push({type:'input_image',image_url:image,detail:'high'});const payload={model:MODEL(),store:false,input:[{role:'developer',content:[{type:'input_text',text:fidelity}]},{role:'user',content:userContent}],text:{format:{type:'json_schema',name,schema,strict:true}}},payloadText=JSON.stringify(payload),started=Date.now(),timeoutMs=Number(process.env.OPENAI_TIMEOUT_MS||120000),input=process.env.NODE_ENV!=='production'?await imageDiagnostics(image):undefined;diagnosticLog('inizio richiesta',{...context,stage:name,model:MODEL(),endpoint:OPENAI_ENDPOINT,timeoutMs,payloadBytes:Buffer.byteLength(payloadText),image:input});let response,json,requestId;
  try{response=await fetch(OPENAI_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:payloadText,signal:AbortSignal.timeout(timeoutMs)});requestId=response.headers?.get?.('x-request-id')||response.headers?.get?.('request-id');const raw=response.text?await response.text():JSON.stringify(await response.json());try{json=JSON.parse(raw)}catch{json={error:{type:'invalid_json_response',message:raw.slice(0,2000)}}}const error=json.error;diagnosticLog('fine richiesta',{...context,stage:name,durationMs:Date.now()-started,status:response.status,requestId,errorCode:error?.code,errorType:error?.type,errorMessage:error?.message,errorParam:error?.param,schemaError:/schema|structured/i.test(`${error?.type} ${error?.code} ${error?.message}`),imageInputError:/image|base64|mime|format/i.test(`${error?.type} ${error?.code} ${error?.message}`),payloadTooLarge:response.status===413||/too large|size|limit/i.test(error?.message||'')});if(!response.ok)throw Object.assign(new Error(error?.message||'Errore durante la scansione Vision.'),{status:response.status,code:error?.code||'openai_error',type:error?.type,requestId,param:error?.param,stage:name,durationMs:Date.now()-started})}catch(error){const timedOut=error?.name==='TimeoutError'||error?.name==='AbortError';diagnosticLog('errore richiesta',{...context,stage:name,durationMs:Date.now()-started,status:response?.status,code:error.code,type:error.type||error.name,message:error.message,requestId:error.requestId||requestId,timeout:timedOut,stack:error.stack,...safeStringDetails(OPENAI_ENDPOINT)});if(timedOut)throw Object.assign(new Error(`Timeout OpenAI dopo ${timeoutMs} ms.`),{status:504,code:'openai_timeout',type:error.name,requestId,stage:name,durationMs:Date.now()-started});if(!response)throw phaseError(error,'fetch_responses_api','callVision',OPENAI_ENDPOINT);throw error}
  try{return JSON.parse(outputText(json))}catch(error){diagnosticLog('errore Structured Outputs',{...context,stage:name,durationMs:Date.now()-started,requestId,message:error.message,responseTypes:(json.output||[]).map(x=>x.type)});throw Object.assign(new Error('La risposta Vision non è JSON valido.'),{code:'openai_structured_output_invalid',type:error.name,requestId,stage:name})}
}

export function computeCrop(region,width,height,retry=false){
  const box={x:region.x/1000*width,y:region.y/1000*height,width:region.width/1000*width,height:region.height/1000*height};
  const margin=Math.max(6,Math.round(Math.min(width,height)*(retry?.01:.025)));
  const left=Math.max(0,Math.floor(box.x-margin)),top=Math.max(0,Math.floor(box.y-margin));
  const right=Math.min(width,Math.ceil(box.x+box.width+margin)),bottom=Math.min(height,Math.ceil(box.y+box.height+margin));
  return{left,top,width:Math.max(1,right-left),height:Math.max(1,bottom-top)};
}
async function makeCrop(page,info,region,retry=false){
  const pixelBox=computeCrop(region,info.width,info.height,retry);let pipeline=sharp(page).extract(pixelBox);const target=retry?2400:region.smallText?1900:1500;
  if(pixelBox.width<target)pipeline=pipeline.resize({width:Math.min(2800,target),withoutEnlargement:false,kernel:'lanczos3'});
  const buffer=await pipeline.jpeg({quality:96,chromaSubsampling:'4:4:4'}).toBuffer();return{image:dataUrl(buffer),pixelBox};
}
function layoutPrompt(page){return `Pagina ${page}. Prima rileva soltanto il layout visivo. Individua colonne, sezioni, intestazioni, blocchi con piatti e prezzi e note a fondo pagina. Crea al massimo ${MAX_BLOCKS} regioni logiche significative: non dividere meccanicamente la pagina a metà. Ogni regione deve includere, quando possibile, nome piatto, descrizione e prezzo collegato, con un piccolo contesto circostante. Non tagliare righe o prezzi. Usa coordinate normalizzate 0-1000 relative all'immagine orientata. Assegna readingOrder dall'alto verso il basso e da sinistra verso destra, e columnIndex coerente. Marca smallText quando servirà ingrandire. Non trascrivere ancora il contenuto.`}
function blockPrompt(region,page,retry){return `Analizza esclusivamente questo crop della pagina ${page}, blocco ${region.blockId}, colonna ${region.columnIndex}, ordine ${region.readingOrder}, tipo ${region.kind}.${retry?' Questo è il secondo e ultimo tentativo con crop più stretto e risoluzione maggiore.':''}
Trascrivi prima ogni riga visibile in rawTextLines, nell'ordine, assegnando ID ${region.blockId}-L1, ${region.blockId}-L2, ecc. Poi struttura categoria, piatti, descrizioni, prezzi, varianti, formati, supplementi, allergeni e note. Collega ogni campo ai sourceLineIds usati. Ogni riga non assegnata deve finire in unclassifiedText: non scartare nulla.
Un prezzo può appartenere solo a un piatto nello stesso crop e con relazione visiva chiara; non importare associazioni da altri blocchi o colonne. Numerazioni, allergeni e grammature (es. 250 g) non sono prezzi. Non unire righe se non è chiaro. Non inventare ingredienti o prezzi. Se il testo è piccolo, sfocato o tagliato, usa qualityWarning e confidence low.`}

function allItems(block){return(block.categories||[]).flatMap(c=>c.items||[])}
function usedLineIds(block){const used=new Set();for(const c of block.categories||[]){for(const id of c.sourceLineIds||[])used.add(id);for(const item of c.items||[])for(const id of item.sourceLineIds||[])used.add(id)}for(const x of block.unclassifiedText||[])for(const id of x.sourceLineIds||[])used.add(id);return used}
function ensureCoverage(block){const used=usedLineIds(block),missing=(block.rawTextLines||[]).filter(x=>!used.has(x.id));if(missing.length){block.unclassifiedText.push(...missing.map(x=>({text:x.text,confidence:'low',sourceLineIds:[x.id]})));block.warnings.push('Righe visibili non assegnate recuperate come testo non classificato.')}return block}
export function shouldRetry(block){const items=allItems(block),raw=block.rawTextLines?.length||0,unc=block.unclassifiedText?.length||0;const critical=items.flatMap(x=>[x.confidence?.name,x.confidence?.price]).filter(Boolean);const low=critical.filter(x=>x==='low').length;return block.blockConfidence==='low'||Boolean(block.qualityWarning)||(critical.length>0&&low/critical.length>.25)||(raw>=4&&unc/raw>.3)||(raw>=5&&items.length===0)}
function scoreBlock(block){const items=allItems(block),critical=items.flatMap(x=>[x.confidence?.name,x.confidence?.price]).filter(Boolean);return confValue[block.blockConfidence] * 6+items.length*3+critical.reduce((n,x)=>n+confValue[x],0)-(block.unclassifiedText?.length||0)*1.5-(block.qualityWarning?4:0)}

const menuWords=new Set(['antipasti','antipasto','primi','secondi','contorni','pizze','pizza','dolci','dessert','bevande','bibite','vini','birre','cocktail','insalate','panini','hamburger','carne','pesce','paste','risotti','specialita','menu']);
const placeholder=name=>norm(name)==='da classificare';
const knownMenuCategory=name=>norm(name).split(' ').some(x=>menuWords.has(x));
const evidenceOrder=cat=>Math.min(...(cat._evidence||[]).map(x=>x.readingOrder),Number.MAX_SAFE_INTEGER);
const evidenceColumn=cat=>cat._evidence?.[0]?.columnIndex;
const isSpurious=cat=>{const ev=cat._evidence?.[0]||{},compact=norm(cat.name).replace(/\s/g,'');return compact.length>=2&&compact.length<=4&&cat.confidence==='low'&&cat.items.length<=1&&!knownMenuCategory(cat.name)&&ev.kind!=='heading'};
const findContinuation=(categories,source)=>{const order=evidenceOrder(source),column=evidenceColumn(source);const valid=categories.filter(c=>c!==source&&!placeholder(c.name)&&!isSpurious(c)&&!c._removed&&evidenceColumn(c)===column);const previous=valid.filter(c=>evidenceOrder(c)<order).sort((a,b)=>evidenceOrder(b)-evidenceOrder(a))[0];if(previous&&order-evidenceOrder(previous)<=1)return previous;const next=valid.filter(c=>evidenceOrder(c)>order).sort((a,b)=>evidenceOrder(a)-evidenceOrder(b))[0];return next&&evidenceOrder(next)-order<=1?next:null};
const pushUnique=(target,item)=>{if(!target.items.some(x=>norm(x.name)===norm(item.name)&&norm(x.description)===norm(item.description)&&priceNorm(x.price)===priceNorm(item.price)))target.items.push(item)};
function fallbackCategory(page,reason,evidence){let target=page.categories.find(c=>placeholder(c.name));if(!target){target={_id:`p${page.page}-fallback`,name:'DA CLASSIFICARE',confidence:'low',sourceLineIds:[],items:[],reason,_evidence:evidence?[evidence]:[]};page.categories.push(target)}target.reason=target.reason||reason;return target}
export function validateStructureHeuristics(page){const changes=[];for(const cat of [...page.categories].sort((a,b)=>evidenceOrder(a)-evidenceOrder(b))){const ev=cat._evidence?.[0]||{},spurious=isSpurious(cat);if(placeholder(cat.name)||spurious){const target=findContinuation(page.categories,cat);if(target){for(const item of cat.items)pushUnique(target,item);if(spurious)page.unclassifiedText.push({text:cat.name,confidence:cat.confidence,page:page.page,blockId:ev.blockId,sourceLineIds:cat.sourceLineIds||[]});changes.push({original:cat.name,final:target.name,reason:spurious?'frammento OCR; continuità con la categoria precedente':'continuità di colonna senza nuova intestazione',confidence:cat.confidence,rule:spurious?'short_ocr_fragment':'layout_continuity'});cat.items=[];cat._removed=true}else if(spurious){page.unclassifiedText.push({text:cat.name,confidence:cat.confidence,page:page.page,blockId:ev.blockId,sourceLineIds:cat.sourceLineIds||[]});if(cat.items.length){const fallback=fallbackCategory(page,'categoria non leggibile',ev);for(const item of cat.items)pushUnique(fallback,item)}changes.push({original:cat.name,final:cat.items.length?'DA CLASSIFICARE':'testo non classificato',reason:'categoria breve senza supporto visivo',confidence:cat.confidence,rule:'short_ocr_fragment'});cat.items=[];cat._removed=true}else if(placeholder(cat.name)){cat.reason=cat.reason||'intestazione mancante';changes.push({original:cat.name,final:cat.name,reason:cat.reason,confidence:cat.confidence,rule:'ambiguous_fallback'})}}
  }
  page.categories=page.categories.filter(c=>!c._removed&&(c.items.length||placeholder(c.name)));if(page.debug)page.debug.validation=[...(page.debug.validation||[]),...changes];return page}

function validationPayload(page){return{page:page.page,layoutAmbiguous:page._layoutAmbiguous,categories:page.categories.map(c=>({categoryId:c._id,name:c.name,confidence:c.confidence,reason:c.reason||null,evidence:c._evidence,items:c.items.map(i=>({itemId:i._id,name:i.name,confidence:i.confidence?.name,blockId:i.blockId,columnIndex:i.columnIndex}))})),unclassifiedText:page.unclassifiedText.map(x=>({text:x.text,confidence:x.confidence,blockId:x.blockId}))}}
function applyAiCorrections(page,corrections){const changes=[];for(const fix of corrections||[]){const source=page.categories.find(c=>c._id===fix.categoryId),target=page.categories.find(c=>c._id===fix.targetCategoryId);if(fix.action==='move_item'&&source&&target&&source!==target){const index=source.items.findIndex(i=>i._id===fix.itemId);if(index>=0){const[item]=source.items.splice(index,1);pushUnique(target,item);changes.push({original:source.name,final:target.name,reason:fix.reason,confidence:item.confidence?.name,rule:'ai_structural_move'})}}else if(fix.action==='merge_categories'&&source&&target&&source!==target&&norm(source.name)===norm(target.name)){for(const item of source.items)pushUnique(target,item);source.items=[];source._removed=true;changes.push({original:source.name,final:target.name,reason:fix.reason,confidence:source.confidence,rule:'ai_exact_duplicate_merge'})}else if(fix.action==='remove_category'&&source&&!source.items.length){page.unclassifiedText.push({text:source.name,confidence:source.confidence,page:page.page,sourceLineIds:source.sourceLineIds||[]});source._removed=true;changes.push({original:source.name,final:'testo non classificato',reason:fix.reason,confidence:source.confidence,rule:'ai_spurious_category'})}}
  page.categories=page.categories.filter(c=>!c._removed);if(page.debug)page.debug.validation=[...(page.debug.validation||[]),...changes];return page}
async function validateStructureWithAI(page){const prompt=`Controlla soltanto la struttura JSON seguente. Non hai immagini e non devi rileggere o riscrivere il menu. Puoi solo rimuovere categorie spurie vuote, unire categorie con nome realmente duplicato, spostare itemId tra categoryId già esistenti o lasciare elementi non classificati. Non creare categorie o piatti. Non modificare nomi, descrizioni, prezzi o ingredienti. Usa coordinate, colonna, ordine e confidence. "DA CLASSIFICARE" è l'ultima possibilità. Restituisci soltanto correzioni necessarie.\n${JSON.stringify(validationPayload(page))}`;try{const result=await callVision({prompt,schema:structuralValidationSchema,name:'menu_structural_validation'});return applyAiCorrections(page,result.corrections)}catch(error){page.warnings.push('Validazione strutturale AI non disponibile; applicate le regole locali.');return page}}

function addCoherenceWarnings(page){const items=page.categories.flatMap(c=>c.items),without=items.filter(x=>!x.price).length;if(without)page.warnings.push(`${without} piatti senza prezzo: verificare nella revisione.`);if(page.categories.some(c=>!c.items.length))page.warnings.push('Sono presenti categorie vuote.');if(page.unclassifiedText.some(x=>/\b(?:€|eur)\b|\d+[,.]\d{2}\b/i.test(x.text)))page.warnings.push('Possibili prezzi senza piatto nel testo non classificato.');if(page.unclassifiedText.length)page.warnings.push('Possibili elementi del menu non classificati');return page}
export function reconstructPage(page,layout,blocks,debug){
  const result={page,restaurantName:null,categories:[],unclassifiedText:[],warnings:[],_layoutAmbiguous:layout.layoutAmbiguous};let categoryIndex=0,itemIndex=0;
  for(const block of [...blocks].sort((a,b)=>a._block.readingOrder-b._block.readingOrder)){
    result.warnings.push(...(block.warnings||[]).map(x=>`${block._block.blockId}: ${x}`));if(block.qualityWarning)result.warnings.push(`${block._block.blockId}: ${block.qualityWarning}`);
    for(const source of block.categories||[]){const evidence={blockId:block._block.blockId,columnIndex:block._block.columnIndex,readingOrder:block._block.readingOrder,x:block._block.x,y:block._block.y,kind:block._block.kind};let target=!placeholder(source.name)&&result.categories.find(c=>norm(c.name)===norm(source.name)&&c.confidence!=='low'&&source.confidence!=='low');if(!target){target={...source,_id:`p${page}-c${++categoryIndex}`,items:[],_evidence:[evidence]};result.categories.push(target)}else target._evidence.push(evidence);
      for(const item of source.items||[]){const duplicate=target.items.some(x=>norm(x.name)===norm(item.name)&&norm(x.description)===norm(item.description)&&priceNorm(x.price)===priceNorm(item.price));if(!duplicate)target.items.push({...item,_id:`p${page}-i${++itemIndex}`,page,blockId:block._block.blockId,columnIndex:block._block.columnIndex})}
    }
    result.unclassifiedText.push(...(block.unclassifiedText||[]).map(x=>({...x,page,blockId:block._block.blockId})));
  }
  if(layout.layoutAmbiguous)result.warnings.push('Layout ambiguo: verificare l’ordine e le associazioni.');if(layout.pageQuality!=='good')result.warnings.push(layout.pageQuality==='unreadable'?'Foto poco leggibile: scattare una nuova foto più ravvicinata.':'Qualità della pagina non ottimale: verificare i campi incerti.');
  if(debug)result.debug={...debug,validation:[]};return addCoherenceWarnings(validateStructureHeuristics(result));
}

export async function analyzePage(imageUrl,page,{mode=process.env.VISION_SCAN_MODE||'high_accuracy',source='photo'}={}){
  let normalized,pageImage;try{normalized=await sharp(decodeDataUrl(imageUrl)).rotate().jpeg({quality:96,chromaSubsampling:'4:4:4'}).toBuffer({resolveWithObject:true})}catch(error){throw phaseError(error,error.phase||'normalize_image','analyzePage',imageUrl)}try{pageImage=dataUrl(normalized.data);validateImageDataUrl(pageImage)}catch(error){throw phaseError(error,'build_vision_data_url','analyzePage',pageImage)}
  const layout=await callVision({prompt:layoutPrompt(page),image:pageImage,schema:layoutSchema,name:'menu_layout',context:{pageNumber:page,source}});const regions=[...(layout.regions||[])].sort((a,b)=>a.readingOrder-b.readingOrder).slice(0,MAX_BLOCKS),blocks=[],debugBlocks=[];
  for(const region of regions){const firstCrop=await makeCrop(normalized.data,normalized.info,region,false);let chosen=ensureCoverage(await callVision({prompt:blockPrompt(region,page,false),image:firstCrop.image,schema:blockSchema,name:'menu_block',context:{pageNumber:page,source,blockId:region.blockId}})),retried=false,crop=firstCrop;
    if(mode==='high_accuracy'&&shouldRetry(chosen)){const secondCrop=await makeCrop(normalized.data,normalized.info,region,true);const second=ensureCoverage(await callVision({prompt:blockPrompt(region,page,true),image:secondCrop.image,schema:blockSchema,name:'menu_block_retry',context:{pageNumber:page,source,blockId:region.blockId}}));retried=true;if(scoreBlock(second)>scoreBlock(chosen)){chosen=second;crop=secondCrop}}
    chosen._block={...region,pageNumber:page};blocks.push(chosen);if(process.env.NODE_ENV!=='production')debugBlocks.push({region,pixelBox:crop.pixelBox,crop:crop.image,confidence:chosen.blockConfidence,retried});
  }
  const debug=process.env.NODE_ENV==='production'?undefined:{page,pageImage,layout,blocks:debugBlocks};const reconstructed=reconstructPage(page,layout,blocks,debug);return validateStructureWithAI(reconstructed);
}

export function mergePages(pages){const out={restaurantName:pages.find(x=>x.restaurantName)?.restaurantName||null,categories:[],unclassifiedText:[],warnings:[]};for(const page of [...pages].sort((a,b)=>a.page-b.page)){out.warnings.push(...(page.warnings||[]).map(x=>`Pagina ${page.page}: ${x}`));out.unclassifiedText.push(...(page.unclassifiedText||[]));for(const source of page.categories||[]){let target;if(placeholder(source.name)){const column=source.items[0]?.columnIndex??evidenceColumn(source);target=[...out.categories].reverse().find(c=>!placeholder(c.name)&&c.items.some(i=>i.page===page.page-1&&(column==null||i.columnIndex===column)));if(target&&page.debug)page.debug.validation.push({original:source.name,final:target.name,reason:'continuità della categoria dalla pagina precedente',confidence:source.confidence,rule:'cross_page_continuity'})}
      if(!target&&!placeholder(source.name))target=out.categories.find(c=>norm(c.name)===norm(source.name)&&c.confidence!=='low'&&source.confidence!=='low');if(!target){target={...source,items:[]};out.categories.push(target)}for(const item of source.items||[])pushUnique(target,{...item,page:item.page||page.page})}}
  if(process.env.NODE_ENV!=='production')out.debug=pages.map(x=>x.debug).filter(Boolean);return out}
