import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Home,ScanLine,Store,Search,ArrowLeft,Plus,Camera,ImagePlus,ChevronRight,Trash2,Save,Utensils,MapPin,Pencil,Images,X,AlertTriangle,Check,RefreshCw}from'lucide-react';import{db}from'./db';import{recognize}from'./ocr';import{analyzeWithVision,inspectQuality}from'./vision';import'./style.css';import'./review.css';import'./delete.css';import'./pwa.css';import'./capture.css';
const uid=()=>crypto.randomUUID(),emptyForm={name:'',city:'',address:'',cuisine:'',notes:''};
function App(){const[page,setPage]=useState('home'),[restaurants,setRestaurants]=useState([]),[current,setCurrent]=useState(null),[query,setQuery]=useState(''),[toast,setToast]=useState(''),[online,setOnline]=useState(navigator.onLine);
 const reload=()=>db.all().then(x=>setRestaurants(x.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))));useEffect(()=>{reload();const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 const open=r=>{setCurrent(r);setPage('restaurant')}; const goScan=()=>{if(!online){setToast('Connessione Internet necessaria per scansionare un nuovo menu.');setTimeout(()=>setToast(''),4000);return}setCurrent(null);setPage('scan')};const removeRestaurant=async id=>{await db.delete(id);setCurrent(null);setQuery('');await reload();setPage('home');setToast('Ristorante eliminato');setTimeout(()=>setToast(''),3200)};
 return <div className="shell"><header><button className="brand" onClick={()=>setPage('home')}><span>R</span> RestMenu</button><div className="header-actions"><InstallRestMenu/>{!['home','list'].includes(page)&&<button className="back" onClick={()=>setPage(current?'restaurant':'home')}><ArrowLeft/> Indietro</button>}</div></header>{!online&&<div className="offline-banner">Connessione Internet necessaria per scansionare un nuovo menu.</div>}<main>
 {page==='home'&&<HomePage items={restaurants} query={query} setQuery={setQuery} open={open} scan={goScan}/>} {page==='list'&&<ListPage items={restaurants} open={open}/>} {page==='scan'&&<ScanPage existing={current} online={online} done={async r=>{await db.put(r);await reload();open(r)}}/>} {page==='restaurant'&&current&&<Restaurant r={current} edit={()=>setPage('edit')} add={()=>setPage('scan')} onDelete={removeRestaurant}/>} {page==='edit'&&current&&<Review base={current} title="Modifica menu" saved={async r=>{await db.put(r);setCurrent(r);await reload();setPage('restaurant')}}/>}
 </main>{toast&&<div className="toast" role="status"><Check/> {toast}</div>}<nav><Nav active={page==='home'} icon={Home} label="Home" onClick={()=>setPage('home')}/><Nav active={page==='scan'} icon={ScanLine} label="Scansiona" primary onClick={goScan}/><Nav active={page==='list'} icon={Store} label="Ristoranti" onClick={()=>setPage('list')}/></nav></div>}
function InstallRestMenu(){const[prompt,setPrompt]=useState(null),[guide,setGuide]=useState(false),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent);useEffect(()=>{const capture=e=>{e.preventDefault();setPrompt(e)},installed=()=>setPrompt(null);addEventListener('beforeinstallprompt',capture);addEventListener('appinstalled',installed);return()=>{removeEventListener('beforeinstallprompt',capture);removeEventListener('appinstalled',installed)}},[]);if(standalone||(!prompt&&!isIOS))return null;const install=async()=>{if(isIOS)return setGuide(true);await prompt.prompt();await prompt.userChoice;setPrompt(null)};return <><button className="install-button" onClick={install}>Installa RestMenu</button>{guide&&<div className="install-guide" onMouseDown={e=>e.target===e.currentTarget&&setGuide(false)}><div role="dialog" aria-modal="true"><h2>Installa RestMenu</h2><p>Per installare RestMenu su iPhone:<br/>apri il menu <strong>Condividi</strong> di Safari e scegli <strong>Aggiungi alla schermata Home</strong>.</p><div className="guide-actions"><button className="secondary" onClick={()=>setGuide(false)}>Ho capito</button></div></div></div>}</>}
function Nav({icon:Icon,label,onClick,active,primary}) {return <button className={primary?'nav primary':active?'nav active':'nav'} onClick={onClick}><Icon/><small>{label}</small></button>}
function HomePage({items,query,setQuery,open,scan}){const shown=useMemo(()=>{const q=query.toLowerCase();return items.filter(r=>[r.name,r.city,r.cuisine,...(r.menu||[]).flatMap(c=>c.items.map(i=>i.name))].join(' ').toLowerCase().includes(q))},[items,query]);return <><section className="hero"><p className="eyebrow">IL TUO ARCHIVIO GASTRONOMICO</p><h1>Ogni menu,<br/><em>sempre con te.</em></h1><p>Scansiona, organizza e ritrova i tuoi ristoranti preferiti.</p><button className="cta" onClick={scan}><Camera/> Scansiona un menu</button></section><section className="content"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca ristorante, città o piatto..."/></div><div className="section-title"><h2>I tuoi ristoranti</h2><span>{shown.length}</span></div>{!shown.length?<Empty scan={scan} search={query}/>:<div className="grid">{shown.map(r=><Card key={r.id} r={r} open={open}/>)}</div>}</section></>}
function Empty({scan,search}){return <div className="empty"><div><Utensils/></div><h3>{search?'Nessun risultato':'Il tuo archivio è vuoto'}</h3><p>{search?'Prova con un altro nome o piatto.':'Fotografa il tuo primo menu e trasformalo in pochi istanti.'}</p>{!search&&<button className="secondary" onClick={scan}><Plus/> Aggiungi ristorante</button>}</div>}
function Card({r,open}){return <button className="card" onClick={()=>open(r)}><div className="monogram">{r.name[0]}</div><div><h3>{r.name}</h3><p>{[r.city,r.cuisine].filter(Boolean).join(' · ')||'Dettagli non inseriti'}</p><small>Aggiornato {new Date(r.updatedAt).toLocaleDateString('it-IT')}</small></div><ChevronRight/></button>}
function ListPage({items,open}){return <section className="content top"><div className="section-title"><div><p className="eyebrow">ARCHIVIO</p><h1>Ristoranti</h1></div><span>{items.length}</span></div>{!items.length?<Empty/>:<div className="grid">{items.map(r=><Card key={r.id} r={r} open={open}/>)}</div>}</section>}
function ScanPage({existing,done,online}){const[step,setStep]=useState(existing?1:0),[form,setForm]=useState(existing||emptyForm),[files,setFiles]=useState([]),[previews,setPreviews]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[status,setStatus]=useState(''),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>()=>previews.forEach(URL.revokeObjectURL),[]);const pick=async e=>{const incoming=[...e.target.files].filter(f=>f.type.startsWith('image/'));e.target.value='';const unique=incoming.filter(f=>!files.some(x=>x.name===f.name&&x.size===f.size));setFiles(v=>[...v,...unique]);setPreviews(v=>[...v,...unique.map(URL.createObjectURL)]);const checks=await Promise.all(unique.map(inspectQuality)),issues=checks.flat();setError(issues.length?'Questa foto potrebbe non essere sufficientemente leggibile. Ti consigliamo di rifarla più da vicino. Puoi comunque provare la scansione.':'')};
 const analyze=async()=>{if(!files.length)return setError('Aggiungi almeno una fotografia.');setBusy(true);setError('');try{let out;try{out=await analyzeWithVision(files,s=>{setStatus(s);setProgress(s.includes('leggendo')?35:78)})}catch(aiError){if(aiError.fallbackAvailable&&window.confirm(`${aiError.message}\n\nVuoi usare il riconoscimento OCR offline come fallback?`)){setStatus('Uso il riconoscimento offline...');out=await recognize(files,(p,s)=>{setProgress(p);if(s)setStatus(s)})}else throw aiError}if(!out.categories.length&&!out.unclassified.length)throw new Error('Non ho trovato testo leggibile. Prova con una foto più nitida.');const sig=i=>[i.name,i.description,i.price].map(x=>(x||'').trim().toLowerCase()).join('|'),known=new Set((existing?.menu||[]).flatMap(c=>c.items.map(sig)));const fresh=out.categories.map(c=>({...c,items:c.items.filter(i=>!known.has(sig(i)))})).filter(c=>c.items.length);setProgress(100);setResult({...form,id:form.id||uid(),updatedAt:new Date().toISOString(),menu:existing?[...(existing.menu||[]),...fresh]:out.categories,unclassified:[...(existing?.unclassified||[]),...out.unclassified],images:[...(existing?.images||[]),...await Promise.all(files.map(toDataUrl))],ocrText:out.text,warnings:out.warnings||[]});setStep(2)}catch(e){setError(e.message||'Analisi non riuscita. Riprova.')}finally{setBusy(false)}};
 if(step===2)return <Review base={result} title="Controlla il menu" saved={done}/>;
 return <section className="content top narrow"><p className="eyebrow">NUOVA SCANSIONE · {step+1}/2</p><h1>{step===0?'Quale ristorante?':'Fotografa il menu'}</h1><p className="lead">{step===0?'Bastano poche informazioni. Potrai completarle più tardi.':'Inquadra bene ogni pagina, con luce uniforme e testo leggibile.'}</p>{step===0?<form onSubmit={e=>{e.preventDefault();setStep(1)}} className="form"><label>Nome ristorante *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="es. Trattoria da Mario"/></label><div className="two"><label>Città<input value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Tipo di cucina<input value={form.cuisine||''} onChange={e=>setForm({...form,cuisine:e.target.value})}/></label></div><label>Indirizzo<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Note<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="cta full">Continua <ChevronRight/></button></form>:<><div className="photo-actions"><label className="photo-action camera-action"><input type="file" accept="image/*" capture="environment" onChange={pick}/><Camera/><span><strong>Scatta foto</strong><small>Usa la fotocamera</small></span></label><label className="photo-action gallery-action"><input type="file" accept="image/*" multiple onChange={pick}/><ImagePlus/><span><strong>Scegli dalla galleria</strong><small>Seleziona anche più pagine</small></span></label></div>{previews.length>0&&<><div className="preview-heading"><strong>{previews.length} {previews.length===1?'fotografia':'fotografie'}</strong><small>Le pagine saranno analizzate in questo ordine</small></div><div className="previews">{previews.map((p,i)=><div key={p}><img src={p}/><button aria-label={`Rimuovi fotografia ${i+1}`} onClick={()=>{setFiles(x=>x.filter((_,j)=>j!==i));setPreviews(x=>x.filter((_,j)=>j!==i))}}><X/></button><span>{i+1}</span></div>)}</div></>}{error&&<p className="error"><AlertTriangle/>{error}</p>}<button disabled={busy||!files.length||!online} className="cta full" onClick={analyze}>{busy?<><RefreshCw className="spin"/> {status||'Analisi'} · {progress}%</>:<><ScanLine/> Analizza menu</>}</button></>}</section>}
const toDataUrl=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});
function Review({base,title,saved}){
 const[data,setData]=useState(()=>structuredClone(base)),[saving,setSaving]=useState(false);
 const patchCat=(ci,p)=>setData(d=>({...d,menu:d.menu.map((c,i)=>i===ci?{...c,...p}:c)}));
 const patchItem=(ci,ii,p)=>setData(d=>({...d,menu:d.menu.map((c,i)=>i===ci?{...c,items:c.items.map((x,j)=>j===ii?{...x,...p,confidence:{...x.confidence,...Object.fromEntries(Object.keys(p).map(k=>[k,'high']))}}:x)}:c)}));
 const addCat=()=>setData(d=>({...d,menu:[...d.menu,{id:uid(),name:'NUOVA CATEGORIA',confidence:'high',items:[]}]}));
 const doubt=v=>v==='low'?' doubtful':v==='medium'?' check':'';
 return <section className="content top review"><p className="eyebrow">REVISIONE</p><h1>{title==='Controlla il menu'?'Controlla la scansione':title}</h1><p className="lead">Confronta il risultato con le foto. Solo i campi colorati richiedono attenzione.</p>{data.warnings?.map((warning,i)=><p className="error" key={i}><AlertTriangle/>{warning}</p>)}
 {data.images?.length>0&&<div className="compare"><h2>Fotografie originali</h2><div className="photos">{data.images.map((src,i)=><figure key={i}><img src={src}/><figcaption>Pagina {i+1}</figcaption></figure>)}</div></div>}
 {data.menu.map((c,ci)=><div className="category-edit" key={c.id}><div className="cat-head"><input className={doubt(c.confidence)} aria-label="Categoria" value={c.name} onChange={e=>patchCat(ci,{name:e.target.value,confidence:'high',reason:null})}/><button className="icon" onClick={()=>setData(d=>({...d,menu:d.menu.filter((_,i)=>i!==ci)}))}><Trash2/></button></div>{c.name==='DA CLASSIFICARE'&&c.reason&&<p className="muted">Motivo: {c.reason}</p>}{c.items.map((it,ii)=><div className="item-edit" key={it.id}><div className="item-row"><input className={doubt(it.confidence?.name)} value={it.name} onChange={e=>patchItem(ci,ii,{name:e.target.value})} placeholder="Nome piatto"/><div className={'price'+doubt(it.confidence?.price)}><span>€</span><input value={it.price} onChange={e=>patchItem(ci,ii,{price:e.target.value.replace(/[^\d,.]/g,'')})} placeholder="—"/></div><button className="icon" onClick={()=>patchCat(ci,{items:c.items.filter((_,i)=>i!==ii)})}><Trash2/></button></div><textarea className={doubt(it.confidence?.description)} value={it.description} onChange={e=>patchItem(ci,ii,{description:e.target.value})} placeholder="Descrizione (facoltativa)"/></div>)}<button className="text-btn" onClick={()=>patchCat(ci,{items:[...c.items,{id:uid(),name:'',description:'',price:'',available:true,confidence:{name:'high',description:'high',price:'high'}}]})}><Plus/> Aggiungi piatto</button></div>)}
 {data.unclassified?.length>0&&<section className="unclassified"><h2><AlertTriangle/> Righe non riconosciute</h2><p>Nessun testo è stato eliminato. Correggi o usa queste righe per completare il menu.</p>{data.unclassified.map((row,i)=><div key={row.id||i}><textarea value={row.text} onChange={e=>setData(d=>({...d,unclassified:d.unclassified.map((r,j)=>j===i?{...r,text:e.target.value,confidence:'high'}:r)}))}/><button className="icon" onClick={()=>setData(d=>({...d,unclassified:d.unclassified.filter((_,j)=>j!==i)}))}><Trash2/></button></div>)}</section>}
 <button className="secondary full" onClick={addCat}><Plus/> Aggiungi categoria</button><button className="cta full sticky" disabled={saving||!data.menu.length} onClick={async()=>{setSaving(true);await saved({...data,updatedAt:new Date().toISOString()})}}><Save/> {saving?'Salvataggio...':'Salva menu'}</button></section>
}
function Restaurant({r,edit,add,onDelete}){const[photos,setPhotos]=useState(false),[confirming,setConfirming]=useState(false),[deleting,setDeleting]=useState(false);return <section className="content top restaurant"><p className="eyebrow">RISTORANTE</p><h1>{r.name}</h1><div className="meta">{r.city&&<span><MapPin/>{r.city}</span>}{r.cuisine&&<span><Utensils/>{r.cuisine}</span>}</div><div className="actions"><button className="secondary" onClick={edit}><Pencil/> Modifica menu</button><button className="secondary" onClick={add}><ImagePlus/> Aggiungi foto</button>{r.images?.length>0&&<button className="secondary" onClick={()=>setPhotos(!photos)}><Images/> Foto originali</button>}</div>{photos&&<div className="photos">{r.images.map((x,i)=><img src={x} key={i}/>)}</div>}<div className="menu">{r.menu?.map(c=><section key={c.id}><h2>{c.name}</h2>{c.items.filter(i=>i.available!==false).map(i=><article key={i.id}><div><h3>{i.name}</h3>{i.description&&<p>{i.description}</p>}</div><strong>{i.price?`€ ${i.price}`:'—'}</strong></article>)}</section>)}</div><div className="danger-zone"><p>Gestione ristorante</p><button className="delete-trigger" onClick={()=>setConfirming(true)}><Trash2/> Elimina ristorante</button></div>{confirming&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setConfirming(false)}><div className="confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><div className="danger-icon"><Trash2/></div><h2 id="delete-title">Eliminare il ristorante?</h2><p>Vuoi davvero eliminare questo ristorante? Verranno eliminati anche il menu e le fotografie associate.</p><div><button className="secondary" disabled={deleting} onClick={()=>setConfirming(false)}>Annulla</button><button className="delete-final" disabled={deleting} onClick={async()=>{setDeleting(true);await onDelete(r.id)}}>{deleting?'Eliminazione...':'Elimina definitivamente'}</button></div></div></div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Service worker non registrato',error)));
