import{preprocessImage}from'./image.js';
const id=()=>crypto.randomUUID();
const categoryHints=/^(antipasti|starters?|appetizers?|primi|first courses?|secondi|main courses?|contorni|sides?|dolci|desserts?|bevande|drinks?|vini|wines?|pizze|insalate|salads?|panini|specialità|specialties|menu|menù)$/i;
const normalize=s=>s.replace(/\s+/g,' ').trim();
export function extractPrice(raw){const s=raw.trim();let m=s.match(/(?:^|\s{2,})(€\s*\d{1,3}(?:[.,]\d{1,2})?|\d{1,3}(?:[.,]\d{1,2})?\s*€?|\d{1,3}[.,]\d{1,2})\s*$/),aligned=!!m;if(!m)m=s.match(/(€\s*\d{1,3}(?:[.,]\d{1,2})?|\d{1,3}(?:[.,]\d{1,2})?\s*€|\d{1,3}[.,]\d{1,2})\s*$/);if(!m)return null;const token=m[1],digits=token.replace(/[^\d.,]/g,'').replace('.',',');if(!/[€,.]/.test(token)&&!aligned)return null;return{price:digits,rest:normalize(s.slice(0,m.index)),raw:token}}
const level=v=>v>=82?'high':v>=55?'medium':'low';
const asLines=input=>typeof input==='string'?input.split(/\r?\n/).filter(x=>x.trim()).map(text=>({text:normalize(text),confidence:70,page:0,box:null})):input.filter(x=>x.text?.trim()).map(x=>({...x,text:normalize(x.text)}));
export function parseMenu(input){const lines=asLines(input);let categories=[],cat=null,pending=null,unclassified=[];const ensure=()=>cat||(cat={id:id(),name:'DA CLASSIFICARE',confidence:'low',items:[]},categories.push(cat),cat);const flush=(asItem=false)=>{if(pending){if(asItem&&cat)cat.items.push({id:id(),name:pending.text,description:'',price:'',available:true,confidence:{name:level(pending.confidence),description:'high',price:'low'},source:{page:pending.page,box:pending.box}});else unclassified.push({...pending,id:id(),confidence:level(pending.confidence)})}pending=null};
 for(const line of lines){const text=line.text,price=extractPrice(text),plain=price?.rest||text;const isCat=!price&&(categoryHints.test(text)||(text.length<35&&text===text.toUpperCase()&&/[A-ZÀ-Ù]/.test(text)&&!/[.!?,;:]$/.test(text)));
  if(isCat){flush(true);cat={id:id(),name:plain.replace(/[^\p{L}\d&'\s-]/gu,'').trim(),confidence:level(line.confidence),items:[]};categories.push(cat);continue}
  if(price){const c=ensure();if(plain){flush();c.items.push({id:id(),name:plain,description:'',price:price.price,available:true,confidence:{name:level(line.confidence),description:'high',price:level(Math.min(95,line.confidence+5))},source:{page:line.page,box:line.box}})}else if(pending){c.items.push({id:id(),name:pending.text,description:'',price:price.price,available:true,confidence:{name:level(pending.confidence),description:'high',price:level(line.confidence)},source:{page:pending.page,box:pending.box}});pending=null}else unclassified.push({...line,id:id(),confidence:level(line.confidence)});continue}
  const c=ensure(),last=c.items.at(-1);if(last&&!last.description&&line.page===last.source?.page){last.description=text;last.confidence.description=level(line.confidence);last.source.descriptionBox=line.box}else if(pending){c.items.push({id:id(),name:pending.text,description:text,price:'',available:true,confidence:{name:level(pending.confidence),description:level(line.confidence),price:'low'},source:{page:pending.page,box:pending.box,descriptionBox:line.box}});pending=null}else pending=line
 }
 flush(true);return{categories:categories.filter(c=>c.items.length||c.name!=='DA CLASSIFICARE'),unclassified};}
function linesFromData(data,page){const lines=[];const walk=node=>{if(!node)return;if(Array.isArray(node))return node.forEach(walk);if(node.text&&node.bbox&&(node.words||node.baseline)){lines.push({text:node.text,confidence:node.confidence??data.confidence,box:node.bbox,page});return}for(const key of['blocks','paragraphs','lines'])if(node[key])walk(node[key])};walk(data.blocks);if(!lines.length)return data.text.split(/\r?\n/).filter(Boolean).map(text=>({text,confidence:data.confidence,page,box:null}));return lines}
export function mergeResults(pages){const categories=[],unclassified=[];for(const parsed of pages){unclassified.push(...parsed.unclassified);for(const cat of parsed.categories){let dest=categories.find(x=>x.name.toLowerCase()===cat.name.toLowerCase());if(!dest){dest={...cat,items:[]};categories.push(dest)}for(const item of cat.items){const key=item.name.toLowerCase().replace(/[^\p{L}\d]/gu,'');if(!dest.items.some(x=>x.name.toLowerCase().replace(/[^\p{L}\d]/gu,'')===key))dest.items.push(item)}}}return{categories,unclassified}}
export async function recognize(files,onProgress){const{createWorker,PSM}=await import('tesseract.js');const worker=await createWorker(['ita','eng'],1,{logger:m=>m.status==='recognizing text'&&onProgress(Math.round(m.progress*100))});await worker.setParameters({tessedit_pageseg_mode:PSM.AUTO,preserve_interword_spaces:'1',user_defined_dpi:'300'});const pages=[],texts=[];for(let i=0;i<files.length;i++){onProgress(0,`Miglioro pagina ${i+1} di ${files.length}`);const processed=await preprocessImage(files[i]);onProgress(2,`Leggo pagina ${i+1} di ${files.length}`);const{data}=await worker.recognize(processed,{}, {text:true,blocks:true});texts.push(data.text);pages.push(parseMenu(linesFromData(data,i)))}await worker.terminate();return{text:texts.join('\n\n'),...mergeResults(pages)}}
