const fileData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
const load=file=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=URL.createObjectURL(file)});
export async function inspectQuality(file){const img=await load(file),warnings=[];if(img.naturalWidth<1100||img.naturalHeight<800)warnings.push('testo potenzialmente troppo piccolo o foto scattata da lontano');const c=document.createElement('canvas'),w=240,h=Math.max(100,Math.round(240*img.naturalHeight/img.naturalWidth));c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,w,h);const d=x.getImageData(0,0,w,h).data,g=new Float32Array(w*h);let mean=0;for(let i=0,p=0;i<d.length;i+=4,p++){g[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];mean+=g[p]}mean/=g.length;if(mean<58)warnings.push('foto molto scura');if(mean>235)warnings.push('foto sovraesposta');let lap=0,n=0;for(let y=1;y<h-1;y++)for(let q=1;q<w-1;q++){const p=y*w+q,v=4*g[p]-g[p-1]-g[p+1]-g[p-w]-g[p+w];lap+=v*v;n++}if(lap/n<75)warnings.push('foto probabilmente sfocata');let edgeInk=0,edgeTotal=0;for(let y=0;y<h;y++)for(let q=0;q<w;q++)if(y<4||q<4||y>=h-4||q>=w-4){edgeTotal++;if(g[y*w+q]<95)edgeInk++}if(edgeInk/edgeTotal>.18)warnings.push('contenuto vicino ai bordi: il menu potrebbe essere tagliato');return warnings}
const id=()=>crypto.randomUUID();
function installVisionDebug(pages){if(!import.meta.env.DEV||!pages?.length)return;window.openRestMenuVisionDebug=()=>{const popup=window.open('','restmenu-vision-debug');if(!popup)return;const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const body=pages.map(p=>`<section><h2>Pagina ${p.page}</h2><div class="page"><img src="${p.pageImage}">${p.layout.regions.map(r=>`<i style="left:${r.x/10}%;top:${r.y/10}%;width:${r.width/10}%;height:${r.height/10}%"><b>${r.readingOrder}</b> ${esc(r.blockId)}</i>`).join('')}</div><div class="crops">${p.blocks.map(b=>`<figure><img src="${b.crop}"><figcaption>${esc(b.region.blockId)} · ${b.confidence}${b.retried?' · retry':''}</figcaption></figure>`).join('')}</div>${p.validation?.length?`<h3>Validazione strutturale</h3><table><thead><tr><th>Originale</th><th>Finale</th><th>Motivo</th><th>Confidence</th><th>Regola</th></tr></thead><tbody>${p.validation.map(v=>`<tr><td>${esc(v.original)}</td><td>${esc(v.final)}</td><td>${esc(v.reason)}</td><td>${esc(v.confidence)}</td><td>${esc(v.rule)}</td></tr>`).join('')}</tbody></table>`:''}</section>`).join('');popup.document.write(`<!doctype html><title>RestMenu Vision debug</title><style>body{font:14px system-ui;margin:20px;background:#f6f3ec;color:#222}.page{position:relative;display:inline-block;max-width:720px}.page>img{display:block;max-width:100%}.page i{position:absolute;box-sizing:border-box;border:3px solid #e33;background:#e332;display:flex;align-items:flex-start;color:#111}.page b{background:#e33;color:white;padding:2px 5px;margin-right:4px}.crops{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.crops img{width:100%}figure{margin:0;background:white;padding:8px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:6px;text-align:left}</style>${body}`);popup.document.close()};console.info('RestMenu Vision debug pronto: window.openRestMenuVisionDebug()')}
const mapResult=json=>{installVisionDebug(json.debug);return{text:'',warnings:json.warnings,pagePreviews:json.pdfPagePreviews||[],categories:json.categories.map(c=>({id:id(),name:c.name,reason:c.reason,confidence:c.confidence,items:c.items.map(x=>({id:id(),name:x.name,description:x.description,price:x.price||'',currency:x.currency,available:true,confidence:x.confidence,variants:x.variants,formats:x.formats,supplements:x.supplements,allergens:x.allergens,number:x.number,page:x.page}))})),unclassified:json.unclassifiedText.map(x=>({id:id(),text:x.text,confidence:x.confidence,page:x.page}))}};
async function scan(payload,onStatus){if(!navigator.onLine)throw Object.assign(new Error('Connessione Internet necessaria per scansionare un nuovo menu.'),{fallbackAvailable:false,code:'offline'});onStatus('Sto leggendo il menu...');const response=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});onStatus('Sto organizzando piatti e prezzi...');const json=await response.json();if(!response.ok)throw Object.assign(new Error(json.error||'Scansione AI non riuscita.'),{fallbackAvailable:json.fallbackAvailable,code:json.code});return mapResult(json)}
export async function analyzeWithVision(files,onStatus){const images=[];for(let i=0;i<files.length;i++)images.push({page:i+1,dataUrl:await fileData(files[i])});return scan({images},onStatus)}
export async function inspectPdfFile(file){const pdf={name:file.name,size:file.size,type:file.type,dataUrl:await fileData(file)},response=await fetch('/api/pdf/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pdf})}),json=await response.json();if(!response.ok)throw Object.assign(new Error(json.error||'Impossibile leggere il PDF.'),{code:json.code});return{...pdf,pageCount:json.pageCount,thumbnail:json.thumbnail}}
export const analyzePdfWithVision=(pdf,onStatus)=>scan({pdf},onStatus);
